# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statistic_figure.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtChart


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, num_tuple):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(252, 223, 86);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        pass_num = num_tuple[0]
        notpass_num = num_tuple[1]
        series = QtChart.QPieSeries()
        series.append('合格:'+str(pass_num), pass_num)
        series.append('不合格:'+str(notpass_num), notpass_num)

        slice_pass = series.slices()[0]
        # slice_pass.setExploded(True)
        slice_pass.setLabelVisible(True)
        slice_pass.setPen(QtGui.QPen(QtCore.Qt.blue, 2))
        slice_pass.setBrush(QtCore.Qt.blue)

        slice_notpass = series.slices()[1]
        slice_notpass.setLabelVisible(True)
        slice_notpass.setPen(QtGui.QPen(QtCore.Qt.red, 2))
        slice_notpass.setBrush(QtCore.Qt.red)

        chart = QtChart.QChart()
        chart.legend().hide()
        chart.addSeries(series)
        chart.createDefaultAxes()

        chart.setAnimationOptions(QtChart.QChart.SeriesAnimations)

        # chart.setTitle("饼图")

        chart.legend().setVisible(True)
        chart.legend().setAlignment(QtCore.Qt.AlignBottom)

        chartview = QtChart.QChartView(chart)
        chartview.setRenderHint(QtGui.QPainter.Antialiasing)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 81))
        self.label.setStyleSheet("background-color: rgb(95, 125, 164);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 90, 701, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        # self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        # self.label_2.setObjectName("label_2")
        # self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout.addWidget(chartview)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(95, 125, 164);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">欢迎来到金相研磨图像识别系统</span></p></body></html>"))
        # self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_4.setText(_translate("MainWindow", "返 回"))
